### ISSUE TITLE
KeyError post420

### ISSUE THREAD

**Issue by firesidegargoyle** [thecodingbob/framebot#1]
The bot immediately throws up the following error message when starting, then shuts down:

Traceback (most recent call last):
  File "C:\tools\framebots\gojira\framebot.py", line 234, in <module>
    album_420_id = config["post420"]["album_id_420"]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'post420'

**Comment by nicholasfreed** [comment]
I've mistakenly uploaded a custom version of the script which included an additional and really specific feature. Sorry for that. It should be fixed now.
